{% set name = "adios2" %}
{% set version = "2.6.0" %}
{% set build = 0 %}
{% set sha256 = "45b41889065f8b840725928db092848b8a8b8d1bfae1b92e72f8868d1c76216c" %}

# ensure mpi is defined (needed for conda-smithy recipe-lint)
{% set mpi = mpi or 'nompi' %}

# prioritize nompi variant via build number
{% if mpi == 'nompi' %}
{% set build = build + 100 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ornladios/ADIOS2/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # FIXME: https://github.com/ornladios/ADIOS2/pull/1805
    - 0001-string-compare.patch

build:
  number: {{ build }}
  # https://github.com/ornladios/ADIOS2/issues/2068
  skip: true  # [python_impl == 'pypy']

  # add build string so packages can depend on
  # mpi or nompi variants
  # dependencies:
  # `pkg * mpi_mpich_*` for mpich
  # `pkg * mpi_*` for any mpi
  # `pkg * nompi_*` for no mpi
  {% if mpi == 'nompi' %}
  {% set mpi_prefix = "nompi" %}
  {% else %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% endif %}
  string: {{ mpi_prefix }}_py{{ py }}h{{ PKG_HASH }}_{{ build }}

  run_exports:
    # strict runtime dependency on build-time MPI flavor
    - {{ name }} * {{ mpi_prefix }}_*
    # https://conda.io/docs/user-guide/tasks/build-packages/variants.html#referencing-subpackages
    # in 0.X.*, newer minor versions are compatible
    - {{ pin_subpackage('adios2', min_pin='x.x', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # TODO: seams incompatible on OSX and too experimental for Windows
    - {{ compiler('fortran') }}  # [linux]
    - make          # [unix]
    - pkg-config    # [unix]
    - cmake >=3.11
  host:
    - {{ mpi }}  # [mpi != 'nompi'] 
    - mpi4py     # [mpi != 'nompi']
    - python
    - numpy >=1.15.0
    - libffi
    # need to list hdf5 twice to get version pinning from conda_build_config
    # and build pinning from {{ mpi_prefix }}
    - hdf5
    - hdf5  >=1.8.13 = {{ mpi_prefix }}_*
    # TODO: Could NOT find ZeroMQ (missing: ZeroMQ_LIBRARY) on Windows
    - zeromq >=4.1  # [not win]
    - bzip2
    - blosc
    - libpng
    # TODO: zfp, sz, mgard
  run:
    - {{ mpi }}  # [mpi != 'nompi']
    - mpi4py     # [mpi != 'nompi']
    - python
    - numpy >=1.15.0

test:
  imports:
    - adios2
  commands:
    # - python -c "import adios2; print(adios2.__version__);"
    - test -f ${PREFIX}/lib/cmake/adios2/adios2-config.cmake                      # [unix]
    - test -f ${PREFIX}/lib/libadios2.so                                          # [linux]
    - otool -L ${PREFIX}/lib/libadios2.dylib                                      # [osx]
    - if exist %LIBRARY_PREFIX%\bin\adios2.dll (exit 0) else (exit 1)             # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\adios2\adios2-config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://www.olcf.ornl.gov/center-projects/adios/
  license: Apache-2.0
  license_file: LICENSE
  summary: Next generation of ADIOS developed in the Exascale Computing Program

  description: |
    ADIOS2 is the latest implementation of the ADaptable Input Output System,
    ADIOS. This brand new architecture was designed to continue supporting the
    performance legacy of ADIOS, and extend its current capabilities to address
    current and future input/output (IO) challenges in the scientific data
    lifecycle through effective research and development (R&D) activities.
  doc_url: https://adios2.readthedocs.io
  dev_url: https://github.com/ornladios/ADIOS2

extra:
  recipe-maintainers:
    - ax3l
    - chuckatkins
    - williamfgc
