{% set name = "adios2" %}
{% set version = "2.8.3" %}
{% set sha256 = "4906ab1899721c41dd918dddb039ba2848a1fb0cf84f3a563a1179b9d6ee0d9f" %}
{% set build = 2 %}

# ensure mpi is defined (needed for conda-smithy recipe-lint)
{% set mpi = mpi or 'nompi' %}

# prioritize nompi variant via build number
{% if mpi == 'nompi' %}
{% set build = build + 100 %}
{% endif %}

# add build string so packages can depend on
# mpi or nompi variants
# dependencies:
# `pkg * mpi_mpich_*` for mpich
# `pkg * mpi_*` for any mpi
# `pkg * nompi_*` for no mpi
{% if mpi == 'nompi' %}
{% set mpi_prefix = "nompi" %}
{% else %}
{% set mpi_prefix = "mpi_" + mpi %}
{% endif %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/ornladios/ADIOS2/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - python-exclude-from-all.patch

build:
  number: {{ build }}
  # https://github.com/ornladios/ADIOS2/issues/2068
  skip: true  # [python_impl == 'pypy']

outputs:
  - name: libadios2
    script: build-libadios.sh  # [unix]
    script: build-libadios.bat  # [win]
    build:
      skip: true  # [python_impl == 'pypy']
      string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}
      # ignore run-exports from Python dependencies
      # note: all of these should be duplicated to host/build in adios2
      # to get the right pins
      ignore_run_exports_from:
        - python
        - mpi4py
        - numpy
      run_exports:
        # strict runtime dependency on build-time MPI flavor
        # patch-releases are not ABI compatible:
        #   https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#referencing-subpackages
        #   https://abi-laboratory.pro/?view=timeline&l=adios2
        - {{ pin_subpackage('libadios2', min_pin='x.x.x', max_pin='x.x.x') }} {{ mpi_prefix }}_*
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - gnuconfig  # [unix]
        # TODO: seems incompatible on OSX and too experimental for Windows
        - {{ compiler('fortran') }}  # [linux]
        - make          # [unix]
        - pkg-config    # [unix]
        - cmake =3.23
        - {{ mpi }}  # [mpi == 'openmpi']
        - flex       # [unix]
        - bison      # [unix]
        #- diff-match-patch  # for ADIOS2 testing on windows, but does not help

        # Needed for Python:
        # Python _build_ is handled here, install in separate output
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
      host:
        - {{ mpi }}  # [mpi != 'nompi']
        - libffi
        # need to list hdf5 twice to get version pinning from conda_build_config
        - hdf5
        - hdf5 * {{ mpi_prefix }}_*
        # TODO: Could NOT find ZeroMQ (missing: ZeroMQ_LIBRARY) on Windows
        - zeromq >=4.1  # [not win]
        - bzip2
        - blosc
        - libpng
        - zfp 0.5  # CMake rejects zfp 1.0.0
        # TODO: sz, mgard

        # Python:
        - mpi4py     # [mpi != 'nompi']
        - python
        - numpy

      run:
        - {{ mpi }}  # [mpi != 'nompi']

    test:
      commands:
        - test -f ${PREFIX}/lib/cmake/adios2/adios2-config.cmake                      # [unix]
        - test -f ${PREFIX}/lib/libadios2_cxx11.so                                    # [linux]
        - otool -L ${PREFIX}/lib/libadios2_cxx11.dylib                                # [osx]
        - if exist %LIBRARY_PREFIX%\bin\adios2_cxx11.dll (exit 0) else (exit 1)       # [win]
        - if exist %LIBRARY_PREFIX%\lib\cmake\adios2\adios2-config.cmake (exit 0) else (exit 1)  # [win]

        # make sure we didn't install Python files
        - test ! -d ${SP_DIR}/adios2  # [unix]
        - if exist %SP_DIR%\adios2 (exit 1) else (exit 0)  # [win]
        - test ! -f ${PREFIX}/bin/bp5dbg  # [unix]
        - if exist %LIBRARY_PREFIX%\bin\bp5dbg (exit 1) else (exit 0)  # [win]

  - name: adios2
    # run cmake component install only
    # previous build actually compiled Python component
    script: build-adios-py.sh  # [unix]
    script: build-adios-py.bat  # [win]
    build:
      skip: true  # [python_impl == 'pypy']
      string: {{ mpi_prefix }}_py{{ py }}h{{ PKG_HASH }}_{{ build }}
      run_exports:
        - {{ pin_subpackage('adios2', min_pin='x.x.x', max_pin='x.x.x') }} {{ mpi_prefix }}_*

    # below requirements should match exactly
    # those in the actual build above
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        - cmake
      host:
        - {{ mpi }}  # [mpi != 'nompi']
        - {{ pin_subpackage("libadios2", exact=True) }}
        - python
        - mpi4py  # [mpi != 'nompi']
        - numpy
      run:
        - {{ mpi }}  # [mpi != 'nompi']
        - {{ pin_subpackage("libadios2", exact=True) }}
        - python
        - mpi4py  # [mpi != 'nompi']
        - numpy
    test:
      # test.imports is unreliable for multiple outputs
      commands:
        # Python package works:
        - python -c "import adios2; print(adios2.__version__)"
        # Python-based scripts are present:
        - bp5dbg --help  # [unix]
        - if exist %LIBRARY_PREFIX%\bin\bp5dbg (exit 0) else (exit 1)  # [win]

about:
  home: https://www.olcf.ornl.gov/center-projects/adios/
  license: Apache-2.0
  license_file: LICENSE
  summary: Next generation of ADIOS developed in the Exascale Computing Program

  description: |
    ADIOS2 is the latest implementation of the ADaptable Input Output System,
    ADIOS. This brand new architecture was designed to continue supporting the
    performance legacy of ADIOS, and extend its current capabilities to address
    current and future input/output (IO) challenges in the scientific data
    lifecycle through effective research and development (R&D) activities.
  doc_url: https://adios2.readthedocs.io
  dev_url: https://github.com/ornladios/ADIOS2

extra:
  feedstock-name: adios2
  recipe-maintainers:
    - ax3l
    - chuckatkins
    - williamfgc
