---
kind: pipeline
name: linux_aarch64_mpimpichnumpy1.18pyth_h0481a29605

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: quay.io/condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_mpimpichnumpy1.18python3.6.____cpythonpython_implcpython
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
    FEEDSTOCK_TOKEN:
      from_secret: FEEDSTOCK_TOKEN
    STAGING_BINSTAR_TOKEN:
      from_secret: STAGING_BINSTAR_TOKEN
  commands:
    - export FEEDSTOCK_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - export FEEDSTOCK_NAME=$(basename ${DRONE_REPO_NAME})
    - sed -i '$ichown -R conda:conda "$FEEDSTOCK_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $FEEDSTOCK_ROOT/.scripts/build_steps.sh
    - echo "Done building"

---
kind: pipeline
name: linux_aarch64_mpimpichnumpy1.18pyth_h3d430a5924

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: quay.io/condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_mpimpichnumpy1.18python3.7.____cpythonpython_implcpython
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
    FEEDSTOCK_TOKEN:
      from_secret: FEEDSTOCK_TOKEN
    STAGING_BINSTAR_TOKEN:
      from_secret: STAGING_BINSTAR_TOKEN
  commands:
    - export FEEDSTOCK_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - export FEEDSTOCK_NAME=$(basename ${DRONE_REPO_NAME})
    - sed -i '$ichown -R conda:conda "$FEEDSTOCK_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $FEEDSTOCK_ROOT/.scripts/build_steps.sh
    - echo "Done building"

---
kind: pipeline
name: linux_aarch64_mpimpichnumpy1.18pyth_hf6a0ce6b4c

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: quay.io/condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_mpimpichnumpy1.18python3.8.____cpythonpython_implcpython
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
    FEEDSTOCK_TOKEN:
      from_secret: FEEDSTOCK_TOKEN
    STAGING_BINSTAR_TOKEN:
      from_secret: STAGING_BINSTAR_TOKEN
  commands:
    - export FEEDSTOCK_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - export FEEDSTOCK_NAME=$(basename ${DRONE_REPO_NAME})
    - sed -i '$ichown -R conda:conda "$FEEDSTOCK_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $FEEDSTOCK_ROOT/.scripts/build_steps.sh
    - echo "Done building"

---
kind: pipeline
name: linux_aarch64_mpimpichnumpy1.19pyth_ha0ce6bdcb9

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: quay.io/condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_mpimpichnumpy1.19python3.9.____cpythonpython_implcpython
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
    FEEDSTOCK_TOKEN:
      from_secret: FEEDSTOCK_TOKEN
    STAGING_BINSTAR_TOKEN:
      from_secret: STAGING_BINSTAR_TOKEN
  commands:
    - export FEEDSTOCK_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - export FEEDSTOCK_NAME=$(basename ${DRONE_REPO_NAME})
    - sed -i '$ichown -R conda:conda "$FEEDSTOCK_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $FEEDSTOCK_ROOT/.scripts/build_steps.sh
    - echo "Done building"

---
kind: pipeline
name: linux_aarch64_mpinompinumpy1.18pyth_hc4784f4923

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: quay.io/condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_mpinompinumpy1.18python3.6.____cpythonpython_implcpython
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
    FEEDSTOCK_TOKEN:
      from_secret: FEEDSTOCK_TOKEN
    STAGING_BINSTAR_TOKEN:
      from_secret: STAGING_BINSTAR_TOKEN
  commands:
    - export FEEDSTOCK_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - export FEEDSTOCK_NAME=$(basename ${DRONE_REPO_NAME})
    - sed -i '$ichown -R conda:conda "$FEEDSTOCK_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $FEEDSTOCK_ROOT/.scripts/build_steps.sh
    - echo "Done building"

---
kind: pipeline
name: linux_aarch64_mpinompinumpy1.18pyth_hf587d9716c

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: quay.io/condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_mpinompinumpy1.18python3.7.____cpythonpython_implcpython
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
    FEEDSTOCK_TOKEN:
      from_secret: FEEDSTOCK_TOKEN
    STAGING_BINSTAR_TOKEN:
      from_secret: STAGING_BINSTAR_TOKEN
  commands:
    - export FEEDSTOCK_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - export FEEDSTOCK_NAME=$(basename ${DRONE_REPO_NAME})
    - sed -i '$ichown -R conda:conda "$FEEDSTOCK_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $FEEDSTOCK_ROOT/.scripts/build_steps.sh
    - echo "Done building"

---
kind: pipeline
name: linux_aarch64_mpinompinumpy1.18pyth_hfc388f315a

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: quay.io/condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_mpinompinumpy1.18python3.8.____cpythonpython_implcpython
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
    FEEDSTOCK_TOKEN:
      from_secret: FEEDSTOCK_TOKEN
    STAGING_BINSTAR_TOKEN:
      from_secret: STAGING_BINSTAR_TOKEN
  commands:
    - export FEEDSTOCK_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - export FEEDSTOCK_NAME=$(basename ${DRONE_REPO_NAME})
    - sed -i '$ichown -R conda:conda "$FEEDSTOCK_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $FEEDSTOCK_ROOT/.scripts/build_steps.sh
    - echo "Done building"

---
kind: pipeline
name: linux_aarch64_mpinompinumpy1.19pyth_h4567de6c8d

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: quay.io/condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_mpinompinumpy1.19python3.9.____cpythonpython_implcpython
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
    FEEDSTOCK_TOKEN:
      from_secret: FEEDSTOCK_TOKEN
    STAGING_BINSTAR_TOKEN:
      from_secret: STAGING_BINSTAR_TOKEN
  commands:
    - export FEEDSTOCK_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - export FEEDSTOCK_NAME=$(basename ${DRONE_REPO_NAME})
    - sed -i '$ichown -R conda:conda "$FEEDSTOCK_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $FEEDSTOCK_ROOT/.scripts/build_steps.sh
    - echo "Done building"

---
kind: pipeline
name: linux_aarch64_mpiopenmpinumpy1.18py_h18a9d269b2

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: quay.io/condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_mpiopenmpinumpy1.18python3.6.____cpythonpython_implcpython
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
    FEEDSTOCK_TOKEN:
      from_secret: FEEDSTOCK_TOKEN
    STAGING_BINSTAR_TOKEN:
      from_secret: STAGING_BINSTAR_TOKEN
  commands:
    - export FEEDSTOCK_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - export FEEDSTOCK_NAME=$(basename ${DRONE_REPO_NAME})
    - sed -i '$ichown -R conda:conda "$FEEDSTOCK_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $FEEDSTOCK_ROOT/.scripts/build_steps.sh
    - echo "Done building"

---
kind: pipeline
name: linux_aarch64_mpiopenmpinumpy1.18py_hbb66a7c5d0

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: quay.io/condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_mpiopenmpinumpy1.18python3.7.____cpythonpython_implcpython
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
    FEEDSTOCK_TOKEN:
      from_secret: FEEDSTOCK_TOKEN
    STAGING_BINSTAR_TOKEN:
      from_secret: STAGING_BINSTAR_TOKEN
  commands:
    - export FEEDSTOCK_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - export FEEDSTOCK_NAME=$(basename ${DRONE_REPO_NAME})
    - sed -i '$ichown -R conda:conda "$FEEDSTOCK_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $FEEDSTOCK_ROOT/.scripts/build_steps.sh
    - echo "Done building"

---
kind: pipeline
name: linux_aarch64_mpiopenmpinumpy1.18py_h05281298ba

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: quay.io/condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_mpiopenmpinumpy1.18python3.8.____cpythonpython_implcpython
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
    FEEDSTOCK_TOKEN:
      from_secret: FEEDSTOCK_TOKEN
    STAGING_BINSTAR_TOKEN:
      from_secret: STAGING_BINSTAR_TOKEN
  commands:
    - export FEEDSTOCK_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - export FEEDSTOCK_NAME=$(basename ${DRONE_REPO_NAME})
    - sed -i '$ichown -R conda:conda "$FEEDSTOCK_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $FEEDSTOCK_ROOT/.scripts/build_steps.sh
    - echo "Done building"

---
kind: pipeline
name: linux_aarch64_mpiopenmpinumpy1.19py_h09f76426af

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: quay.io/condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_mpiopenmpinumpy1.19python3.9.____cpythonpython_implcpython
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
    FEEDSTOCK_TOKEN:
      from_secret: FEEDSTOCK_TOKEN
    STAGING_BINSTAR_TOKEN:
      from_secret: STAGING_BINSTAR_TOKEN
  commands:
    - export FEEDSTOCK_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - export FEEDSTOCK_NAME=$(basename ${DRONE_REPO_NAME})
    - sed -i '$ichown -R conda:conda "$FEEDSTOCK_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $FEEDSTOCK_ROOT/.scripts/build_steps.sh
    - echo "Done building"

